//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDesignPatternsProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bulgarian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bulgarian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareDesignPatternsProject.Properties.Bulgarian", typeof(Bulgarian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пари в сметката:.
        /// </summary>
        internal static string AccountAmount {
            get {
                return ResourceManager.GetString("AccountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това бизнес акаунт ли е? (y/n).
        /// </summary>
        internal static string AccountBusiness {
            get {
                return ResourceManager.GetString("AccountBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акаунтът е създаден!.
        /// </summary>
        internal static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желаете ли кредитна карта? (y/n).
        /// </summary>
        internal static string AccountCreditCard {
            get {
                return ResourceManager.GetString("AccountCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имате следния брой акаунти:.
        /// </summary>
        internal static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямате никакви акаунти.
        /// </summary>
        internal static string AccountMissing {
            get {
                return ResourceManager.GetString("AccountMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на акаунта:.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колко долара искате да депозирате в сметката си?.
        /// </summary>
        internal static string AmountToDeposit {
            get {
                return ResourceManager.GetString("AmountToDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колко пари искате да трансферирате?.
        /// </summary>
        internal static string AmountToTransfer {
            get {
                return ResourceManager.GetString("AmountToTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишете името на сметката, с която искате да извършите транзакция.
        /// </summary>
        internal static string ChooseAccount {
            get {
                return ResourceManager.GetString("ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидна команда. Опитайте отново или напиеште -help.
        /// </summary>
        internal static string CommandError {
            get {
                return ResourceManager.GetString("CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък с всички команди:.
        /// </summary>
        internal static string CommandList {
            get {
                return ResourceManager.GetString("CommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желаете ли да продължите? (y/n).
        /// </summary>
        internal static string TransactionComplete {
            get {
                return ResourceManager.GetString("TransactionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таксата за вашата транзакция е:.
        /// </summary>
        internal static string TransactionPrice {
            get {
                return ResourceManager.GetString("TransactionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете вид транзакция: (transfer/deposit).
        /// </summary>
        internal static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
